-- USER SQL

CREATE USER TEST IDENTIFIED BY pi123456;


-- QUOTAS


-- ROLES
--GRANT "CONNECT" TO "JAVA" ;
--GRANT "RESOURCE" TO "JAVA" ;
GRANT CONNECT,RESOURCE TO TEST;


-- SYSTEM PRIVILEGES
--GRANT CREATE ANY VIEW TO "JAVA" ;
GRANT CREATE ANY VIEW TO TEST;
